[env:esp32-s3-devkitc-1]
platform = espressif32 ; ESP32 平台
board = esp32-s3-devkitc-1 ; ESP32-S3 开发板：1 板
framework = arduino ; Arduino 框架

board_upload.flash_size = 16MB ; 16MB 闪存大小
board_build.partitions = default_16MB.csv ; 默认分区表

; Serial
monitor_speed = 115200 ; 115200 波特率
monitor_filters = esp32_exception_decoder ; 异常解码器：用于解码 ESP32 异常信息

board_build.psram = enabled ; 启用 PSRAM 以提高性能
board_build.arduino.memory_type = qio_opi ; QIO 模式，使用 OPI 接口连接 PSRAM
board_build.psram_type = opi ; OPI 接口连接 PSRAM
board_build.flash_mode = qio ; QIO 模式，使用 OPI 接口连接 PSRAM
board_build.f_flash = 80000000L ; 80MHz 闪存频率

; Build flags
build_flags =
    -DBOARD_HAS_PSRAM ; 启用 PSRAM
    -DCORE_DEBUG_LEVEL=3 ; 核心调试级别：3 = 详细，2 = 基本，1 = 关闭
    -I include ; 包含头文件目录
    -DUSE_UTF8_LONG_NAMES=1 ; 启用 UTF-8 长文件名
    -DSDFAT_FILE_TYPE=1 ; 文件类型：1 = FAT32，0 = FAT16
    -DARDUINO_LOOP_STACK_SIZE=6144 ; 循环栈大小：6144 字节
    -DLOG_LEVEL=2   ; 日志级别：2 = 详细，1 = 基本，0 = 关闭
    -DDISABLE_FS_H_WARNING  ; 禁用 SdFat 的 FS.h 冲突警告
    -DWEBCTRL_ENABLED=1     ; 启用 Web 控制
    -DUSE_AUDIO_LOGGING=false ; 关闭 Audio Tools 日志
    
; Build type
build_type = debug ; 调试模式

; Libraries
lib_deps =
    ; Display
    lovyan03/LovyanGFX@^1.1.12 ; 显示库：用于绘制文本、图像等显示元素
    ; SD
    greiman/SdFat@^2.2.3 ; SD 卡库：用于读写 SD 卡

    ; NFC
    https://github.com/OSSLibraries/Arduino_MFRC522v2.git ; NFC 库：用于读取 NFC 标签

    ; Audio (optional)
    https://github.com/pschatzmann/arduino-audio-tools.git  ; Audio Tools 网络收流层（使用 GitHub 仓库）
    ; espressif/esp32-audioI2S
